from __future__ import annotations

import re
from pathlib import Path
from typing import Any

from ..catalogs import catalog_ids
from ..derivations import derive_swimming_events
from .schema import ValidationIssue


def validate_swimming_event_config(data: dict[str, Any]) -> list[ValidationIssue]:
    issues: list[ValidationIssue] = []

    _expect_catalog_value(issues, "$.distance", data.get("distance"), catalog_ids("swimming", "distances"))
    _expect_catalog_value(issues, "$.nage", data.get("nage"), catalog_ids("swimming", "strokes"))
    _expect_catalog_value(issues, "$.sexe", data.get("sexe"), catalog_ids("common", "sexes"))
    _expect_catalog_value(issues, "$.epreuve", data.get("epreuve"), catalog_ids("swimming", "rounds"))
    _expect_catalog_value(issues, "$.start_side", data.get("start_side"), catalog_ids("common", "sides"))
    _expect_boolean_like(issues, "$.one_is_up", data.get("one_is_up"))

    generated_event_ids = {item["id"] for item in derive_swimming_events()["values"]}
    event_id = f"{data.get('nage')}_{data.get('sexe')}_{data.get('distance')}_{data.get('epreuve')}"
    if event_id not in generated_event_ids:
        issues.append(ValidationIssue("$", f"swimming event {event_id!r} is not generated by the event recipe"))

    annotation = data.get("annotation_simple", {})
    if isinstance(annotation, dict):
        issues.extend(_validate_swimming_annotation(annotation, data))

    for index, video in enumerate(data.get("videos", [])):
        if isinstance(video, dict):
            _expect_catalog_value(issues, f"$.videos[{index}].start_side", video.get("start_side"), catalog_ids("common", "sides"))
            _expect_boolean_like(issues, f"$.videos[{index}].one_is_up", video.get("one_is_up"))

    return issues


def validate_table_tennis_match_manifest(data: list[Any]) -> list[ValidationIssue]:
    issues: list[ValidationIssue] = []
    pattern = re.compile(r"^set_[0-9]+_point_([0-9]+)$")

    for manifest_index, manifest in enumerate(data):
        if not isinstance(manifest, dict):
            continue

        expected_point = 0
        for clip_index, clip in enumerate(manifest.get("game_clips", [])):
            path = f"$[{manifest_index}].game_clips[{clip_index}].name"
            if not isinstance(clip, dict):
                continue
            name = clip.get("name")
            if not isinstance(name, str):
                continue
            match = pattern.match(name)
            if not match:
                issues.append(ValidationIssue(path, "does not match table-tennis set-point clip naming"))
                continue
            point_index = int(match.group(1))
            if point_index != expected_point:
                issues.append(ValidationIssue(path, f"expected point index {expected_point}, got {point_index}"))
            expected_point += 1

        _expect_extension(issues, f"$[{manifest_index}].competition_json_metadata", manifest.get("competition_json_metadata"), {".json"})
        _expect_extension(issues, f"$[{manifest_index}].game_table_perspective", manifest.get("game_table_perspective"), {".json"})
        _expect_extension(issues, f"$[{manifest_index}].game_annotation", manifest.get("game_annotation"), {".csv"})
        _expect_extension(issues, f"$[{manifest_index}].game_image", manifest.get("game_image"), {".jpg", ".jpeg", ".png"})
        _expect_extension(issues, f"$[{manifest_index}].video_name", manifest.get("video_name"), {".mp4", ".mov", ".mkv"})

    return issues


def _validate_swimming_annotation(annotation: dict[str, Any], root: dict[str, Any]) -> list[ValidationIssue]:
    issues: list[ValidationIssue] = []
    _expect_catalog_value(issues, "$.annotation_simple.sport", annotation.get("sport"), {"swimming"})
    _expect_catalog_value(issues, "$.annotation_simple.fieldPresetId", annotation.get("fieldPresetId"), catalog_ids("swimming", "field-presets"))
    _expect_catalog_value(issues, "$.annotation_simple.referenceCorner", annotation.get("referenceCorner"), catalog_ids("common", "reference-corners"))
    _expect_catalog_value(issues, "$.annotation_simple.startSide", annotation.get("startSide"), catalog_ids("common", "sides"))

    event_ids = catalog_ids("swimming", "annotation-events")
    for index, event_id in enumerate(annotation.get("events", [])):
        _expect_catalog_value(issues, f"$.annotation_simple.events[{index}]", event_id, event_ids)

    lanes = set(root.get("lignes", {}).keys()) if isinstance(root.get("lignes"), dict) else set()
    entity_keys: set[str] = set()
    for index, entity in enumerate(annotation.get("entities", [])):
        if not isinstance(entity, dict):
            continue
        key = entity.get("key")
        if isinstance(key, str):
            if key in entity_keys:
                issues.append(ValidationIssue(f"$.annotation_simple.entities[{index}].key", f"duplicate entity key {key!r}"))
            entity_keys.add(key)
        lane = entity.get("lane")
        if lane not in lanes:
            issues.append(ValidationIssue(f"$.annotation_simple.entities[{index}].lane", f"lane {lane!r} is not declared in $.lignes"))

    return issues


def _expect_catalog_value(issues: list[ValidationIssue], path: str, value: Any, allowed: set[str]) -> None:
    if not isinstance(value, str) or value not in allowed:
        values = ", ".join(sorted(allowed))
        issues.append(ValidationIssue(path, f"expected one of: {values}"))


def _expect_boolean_like(issues: list[ValidationIssue], path: str, value: Any) -> None:
    if isinstance(value, bool):
        return
    if value in {"True", "False"}:
        return
    issues.append(ValidationIssue(path, "expected boolean or 'True'/'False' string"))


def _expect_extension(issues: list[ValidationIssue], path: str, value: Any, extensions: set[str]) -> None:
    if not isinstance(value, str):
        return
    suffix = Path(value).suffix.lower()
    if suffix not in extensions:
        values = ", ".join(sorted(extensions))
        issues.append(ValidationIssue(path, f"expected extension in: {values}"))
